### PR TITLE
Upgrade to Gradle 7 and bump dependencies.

### LINKED ISSUE #172: Vulnerabilities in dependencies
We're using the most recent release (0.2.44) and our vulnerability scanner picked up a number of vulnerabilities in some of the adapter's dependencies. Looks like the most severe ones are in:

- com.google.oauth-client:google-oauth-client
- org.json:json
- io.netty:netty-handler
- org.eclipse.jetty.http2:http2-hpack
- io.netty:netty-codec
- com.google.protobuf:protobuf-java
- com.google.code.gson:gson

I'd be happy to take a stab at updating them myself but figured I'd check to see if y'all have an easy process for that first.

### PR DESCRIPTION
**Pull request by craigatron**
fixes #172

### CODE REVIEW

**Comment by craigatron** [comment]
@IvanIsCoding I don't have visibility into that first failure - anything obvious in the logs?

Wasn't able to run the integration tests locally since I don't have permissions on any of those projects but I did build and run the export image successfully.

**Comment by IvanIsCoding** [comment]
@craigatron the export works fine but the Import image is not building this time
```
Step #0 - "basic-test": WARN  com.google.cloud.healthcare.imaging.dicomadapter.GcpMetadataUtil  - Failed to get metadata for instance/attributes/cluster-name with exception {}
Step #0 - "basic-test": com.google.api.client.http.HttpResponseException: 404 Not Found
Step #0 - "basic-test": GET http://metadata/computeMetadata/v1/instance/attributes/cluster-name
Step #0 - "basic-test": Not Found
Step #0 - "basic-test": 
Step #0 - "basic-test": 	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
Step #0 - "basic-test": 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
Step #0 - "basic-test": 	at com.google.cloud.healthcare.imaging.dicomadapter.GcpMetadataUtil.get(GcpMetadataUtil.java:45)
Step #0 - "basic-test": 	at com.google.cloud.healthcare.imaging.dicomadapter.monitoring.MonitoringService.<init>(MonitoringService.java:79)
Step #0 - "basic-test": 	at com.google.cloud.healthcare.imaging.dicomadapter.monitoring.MonitoringService.initialize(MonitoringService.java:112)
Step #0 - "basic-test": 	at com.google.cloud.healthcare.imaging.dicomadapter.ImportAdapter.main(ImportAdapter.java:91)
Step #0 - "basic-test": Exception in thread "main" java.lang.NoSuchMethodError: 'boolean com.google.protobuf.DescriptorProtos$FieldDescriptorProto.getProto3Optional()'
Step #0 - "basic-test": 	at com.google.protobuf.Descriptors$FieldDescriptor.<init>(Descriptors.java:1519)
Step #0 - "basic-test": 	at com.google.protobuf.Descriptors$FieldDescriptor.<init>(Descriptors.java:1064)
Step #0 - "basic-test": 	at com.google.protobuf.Descriptors$Descriptor.<init>(Descriptors.java:942)
Step #0 - "basic-test": 	at com.google.protobuf.Descriptors$Descriptor.<init>(Descriptors.java:655)
Step #0 - "basic-test": 	at com.google.protobuf.Descriptors$FileDescriptor.<init>(Descriptors.java:559)
Step #0 - "basic-test": 	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:331)
Step #0 - "basic-test": 	at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(Descriptors.java:438)
Step #0 - "basic-test": 	at com.google.api.LabelProto.<clinit>(LabelProto.java:54)
Step #0 - "basic-test": 	at com.google.api.MonitoredResourceProto.<clinit>(MonitoredResourceProto.java:86)
Step #0 - "basic-test": 	at com.google.api.MonitoredResource$LabelsDefaultEntryHolder.<clinit>(MonitoredResource.java:158)
Step #0 - "basic-test": 	at com.google.api.MonitoredResource$Builder.internalGetMutableLabels(MonitoredResource.java:824)
Step #0 - "basic-test": 	at com.google.api.MonitoredResource$Builder.putAllLabels(MonitoredResource.java:984)
Step #0 - "basic-test": 	at com.google.cloud.healthcare.imaging.dicomadapter.monitoring.MonitoringService.<init>(MonitoringService.java:99)
Step #0 - "basic-test": 	at com.google.cloud.healthcare.imaging.dicomadapter.monitoring.MonitoringService.initialize(MonitoringService.java:112)
Step #0 - "basic-test": 	at com.google.cloud.healthcare.imaging.dicomadapter.ImportAdapter.main(ImportAdapter.java:91)
Step #0 - "basic-test": 
Step #0 - "basic-test": > Task :import:run FAILED
```

**Comment by IvanIsCoding** [comment]
Also, if you want to run integration tests in your own GCP project, you can change the project in https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/blob/eb6429406cb142e06be16601edecdd8a5ba29a81/integration_test/substitution.py#L2 and run the gcloud command for https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/tree/master/integration_test#how-to-run

The hardcoded gcp-healthcare-oss-test is just for CI/CD, the suggested development is in each developers own project with Cloud Build, Cloud Healthcare, and Cloud Storage APIs enabled.

**Comment by craigatron** [comment]
went down a fun rabbit hole of Java transitive dependencies and found out the redactor package was causing a conflict in proto library versions - put together a PR [here](https://github.com/red1408/deid-redactor/pull/1)

**Comment by craigatron** [comment]
looks good to go, this should be the last one!

**Review by IvanIsCoding — APPROVED** [review]

**Pull request merged**
